CardHolderSite/CardHolderSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("CardStorage.urls"))
]

CardHolderSite/CardStorage/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Storage.as_view(), name="home"),
    path("generator/", GeneratorCard.as_view(), name="generator"),
    path("profile/<int:pk>", ProfileCard.as_view(), name="profile"),
    path("profile/<int:pk>/activate", ActivateCard.as_view(), name="activate"),
    path("profile/<int:pk>/delete", DeleteCard.as_view(), name="delete"),

]

CardHolderSite/CardStorage/models.py
from django.db import models


class Card(models.Model):
    series = models.PositiveIntegerField(verbose_name="Серия")
    number = models.CharField(max_length=20, verbose_name="Номер")
    release_date = models.DateTimeField(verbose_name="Дата создания")
    end_date = models.DateTimeField(verbose_name="Дата окончания активации")
    status = models.BooleanField(verbose_name="Статус")


class CardTransaction(models.Model):
    card_id = models.ForeignKey("Card", on_delete=models.CASCADE, verbose_name="Карта")
    date_use = models.DateTimeField(verbose_name="Дата использования")
    amount = models.IntegerField(verbose_name="Сумма")

CardHolderSite/CardStorage/forms.py
from django import forms

from .models import Card, CardTransaction


class GeneratorForm(forms.Form):
    END_DATE_CHOICES = [
        ('Year', '1  год'),
        ('Six-months', '6 месяцев'),
        ('Month', '1 месяц'),
    ]
    series = forms.IntegerField(max_value=9999, min_value=1, label="Серия")
    end_date = forms.ChoiceField(choices=END_DATE_CHOICES, label="Дата окончания")
    count_card = forms.IntegerField(min_value=1, label="Кол-во карт", required=True)


class SearchForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = [
            "series",
            "number",
            "release_date",
            "end_date",
            "status"
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['series'].required = False
        self.fields['number'].required = False
        self.fields['release_date'].required = False
        self.fields['end_date'].required = False
        self.fields['status'].required = False
        self.fields['status'].value = True


class TransactionForm(forms.ModelForm):
    class Meta:
        model = CardTransaction
        fields = [
            "date_use",
            "amount"
        ]

CardHolderSite/CardStorage/views.py
import datetime
import random

from dateutil.relativedelta import relativedelta
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils import timezone, dateformat
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import GeneratorForm, SearchForm, TransactionForm
from .models import Card, CardTransaction


class ActivateCard(View):
    def get(self, request, pk):
        card = Card.objects.get(pk=pk)
        if card.status:
            Card.objects.filter(pk=card.pk).update(status=False)
        elif card.status == False:
            Card.objects.filter(pk=card.pk).update(status=True)
        return redirect("profile", pk)


class DeleteCard(View):
    def get(self, request, pk):
        Card.objects.get(pk=pk).delete()
        return redirect("home")


class Storage(ListView):
    template_name = "CardStorage/list_card.html"
    model = Card
    context_object_name = "cards"
    form = SearchForm

    def get_queryset(self):
        series = Q(series=self.request.GET.get('series')) if self.request.GET.get('series') else Q()
        number = Q(number__icontains=self.request.GET.get('number')) if self.request.GET.get('number') else Q()
        release_date = Q(release_date__gte=self.request.GET.get('release_date')) if self.request.GET.get(
            'release_date') else Q()
        end_date = Q(end_date__lte=self.request.GET.get('end_date')) if self.request.GET.get('end_date') else Q()
        status = Q(status=self.request.GET.get('status')) if self.request.GET.get('status') else Q()
        if len(self.request.GET):
            object_list = self.model.objects.filter(series & number & release_date & end_date & status)
        else:
            object_list = self.model.objects.all()
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for i in context["cards"]:
            if i.status == True:
                i.status = "Активна"
            elif i.status == False:
                i.status = "Просрочена"
        context["form"] = self.form()
        return context


class ProfileCard(View):
    template_name = "CardStorage/profile.html"
    form_class = TransactionForm

    def get(self, request, pk):
        transactions = CardTransaction.objects.filter(card_id=pk)
        card = Card.objects.get(pk=pk)
        form = self.form_class()
        if card.status == True:
            card.status = "Активна"
        elif card.status == False:
            card.status = "Просрочена"

        context = {
            "card": card,
            "transactions": transactions,
            "form": form
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            date_use = form.cleaned_data["date_use"]
            amount = form.cleaned_data["amount"]
            CardTransaction.objects.create(card_id=Card.objects.get(pk=pk), date_use=date_use, amount=amount)

            return redirect("profile", pk)


class GeneratorCard(View):
    form_class = GeneratorForm
    template_name = "CardStorage/generator_card.html"

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            number_list = list("0123456789")
            time_now = dateformat.format(timezone.now(), 'Y-m-d H:i')
            release_date = datetime.datetime.strptime(time_now, '%Y-%m-%d %H:%M')
            if form.cleaned_data["end_date"] == "Year":
                end_date = release_date + relativedelta(year=1)
            elif form.cleaned_data["end_date"] == "Six-months":
                end_date = release_date + relativedelta(months=6)
            elif form.cleaned_data["end_date"] == "Month":
                end_date = release_date + relativedelta(months=1)

            for _ in range(form.cleaned_data["count_card"]):
                number = ""
                for _ in range(16):
                    number += random.choice(number_list)
                Card.objects.create(
                    series=form.cleaned_data["series"],
                    number=number,
                    release_date=release_date,
                    end_date=end_date,
                    status=True
                )
            return redirect("home")

CardHolderSite/CardStorage/templates/CardStorage/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <title>Сайт тестирования</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body class="bd-example" style="background-color: rgb(238,238,238);">

<div class="container-xl">
    <nav class="navbar sticky-top navbar-expand-lg md-3 mb-4"
         style="background-color: rgba(192,152,213,0.75); border-radius: 10px;">
        <div class="container-fluid px-4">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <a class="navbar-brand col-md-4 " href="{% url 'home' %}">Визитница</a>
                    <li class="nav-item col-4">
                    </li>
                    <li class="nav-item">
                        <a class="navbar-nav nav-link btn btn-outline-light"
                           href="{% url 'generator' %}">Сгенерировать</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-xxl">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

CardHolderSite/CardStorage/templates/CardStorage/generator_card.html
{% extends "CardStorage/base.html" %}
{% block content %}
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    Логин или пароль введены неверно! Попробуйте снова.
</div>
{% endif %}
<div class="form-error">{{ form.non_field_errors }}</div>
<form action="{% url 'generator' %}" method="post">
    {% csrf_token %}
    <div class="container">

        <p>
            <label class="form-label" for="{{ form.series.id_for_label }}">{{form.series.label}}: </label>
            {{ form.series }}
        </p>
        <div class="form-error">{{ form.series.errors }}</div>
        <p>
            <label class="form-label" for="{{ form.end_date.id_for_label }}">{{form.end_date.label}}:</label>
            {{ form.end_date }}
        </p>
        <div class="form-error">{{ form.end_date.errors }}</div>
        <p>
            <label class="form-label" for="{{ form.count_card.id_for_label }}">{{form.count_card.label}}:</label>
            {{ form.count_card }}
        </p>
        <div class="form-error">{{ form.count_card.errors }}</div>

        <button type="submit">Сгенерировать</button>
    </div>
</form>
{% endblock %}

CardHolderSite/CardStorage/templates/CardStorage/list_card.html
{% extends "CardStorage/base.html" %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col text-center">
            <form action="{% url 'home' %}" method="get">
                <div class="row ">
                    <div class="col-md-2 col-sm-3 col-xs-3">
                        <span class="help-block text-muted small-font"> {{form.series.label}}</span>
                        <input type="number" name="series" min="0" id="id_series" class="form-control"/>
                    </div>
                    <div class="col-md-2 col-sm-3 col-xs-3">
                        <span class="help-block text-muted small-font"> {{form.number.label}}</span>
                        <input type="text" name="number" maxlength="20" id="id_number" class="form-control"/>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <span class="help-block text-muted small-font"> {{form.release_date.label}}</span>
                        <input type="text" name="release_date" id="id_release_date" class="form-control"
                               placeholder="Год-Месяц-День Часы:Минуты"/>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <span class="help-block text-muted small-font"> {{form.end_date.label}}</span>
                        <input type="text" name="end_date" id="id_end_date" class="form-control"
                               placeholder="Год-Месяц-День Часы:Минуты"/>

                    </div>
                    <div class="d-flex align-content-end flex-wrap  ">
                        <span class="form-check-inline"> {{form.status.label}}</span>
                        <input type="checkbox" name="status" id="id_status" value=True
                               class="form-check-input align-content-md-end"/>
                    </div>


                    <p>
                        <button type="submit" class="btn btn-secondary">Фильтровать</button>
                    </p>
            </form>
        </div>
    </div>
</div>


<div class="row">
    {% for card in cards %}
    <div class="col-sm-4">
        <div class="card mb-3" style="width: 24rem; border-radius: 25px;">
            <div class="card-body">
                <p>
                <h4 class="card-title text-center">{{card.number}}</h4>
                </p>
                <div class="col-md-8 ">
                    <div class="d-flex justify-content-between ">
                        <h6 class="card-subtitle mb-2 text-muted">Серия: {{ card.series}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">Статус: {{ card.status}}</h6>
                    </div>
                </div>
                <p class="card-text"> Дата активации: {{ card.release_date}}
                    <br>
                    Дата окончания: {{ card.end_date}}
                </p>
                <div class="card text-center">
                    <a href="{% url 'profile' card.pk %}" class="btn btn-outline-primary ">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

CardHolderSite/CardStorage/templates/CardStorage/profile.html
{% extends "CardStorage/base.html" %}
{% block content %}

<div class="d-flex justify-content-center mb-4">
    <div class="card mb-3" style="width: 24rem; border-radius: 25px;">
        <div class="card-body">
            <p>
            <h4 class="card-title text-center">{{card.number}}</h4>
            </p>
            <div class="col-md-8 ">
                <div class="d-flex justify-content-between ">
                    <h6 class="card-subtitle mb-2 text-muted">Серия: {{ card.series}}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">Статус: {{ card.status}}</h6>
                </div>
            </div>
            <p class="card-text"> Дата активации: {{ card.release_date}}
                <br>
                Дата окончания: {{ card.end_date}}
            </p>
            <div class="card text-center">
                <a href="{% url 'delete' card.pk %}" class="btn btn-outline-danger mb-2">Удалить карту</a>
                {% if card.status == "Активна" %}
                <a href="{% url 'activate' card.pk %}" class="btn btn-outline-warning">Деактивировать</a>
                {% else %}
                <a href="{% url 'activate' card.pk %}" class="btn btn-outline-warning">Активировать</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="justify-content-center mb-4">
    <form action="{% url 'profile' card.pk %}" method="post">
        {% csrf_token %}
        <div class="row justify-content-center ">
            <div class="col-md-2 col-sm-3 col-xs-3">
                <span class="help-block text-muted small-font"> {{form.amount.label}}</span>
                <input type="number" name="amount" id="id_amount" class="form-control"/>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-3">
                <span class="help-block text-muted small-font"> {{form.date_use.label}}</span>
                <input type="text" name="date_use" id="id_date_use" class="form-control"/>
            </div>
            <button type="submit" class="ol-md-1 col-sm-2 col-xs-1 btn btn-outline-success">Добавить транзакцию</button>
        </div>
    </form>
</div>
<div class="justify-content-center">
    <div class="row justify-content-center ">
        <div class="col-md-2 col-sm-3 col-xs-3">
            <span class="help-block text-muted small-font"> ID</span>
            {% for i in transactions %}
            <p>
            {{ i.pk }}
                </p>
            {% endfor %}
        </div>
        <div class="col-md-2 col-sm-3 col-xs-3">
            <span class="help-block text-muted small-font"> {{form.amount.label}}</span>
            {% for i in transactions %}
            <p>
            {{ i.amount }}
                </p>
            {% endfor %}
        </div>
        <div class="col-md-2 col-sm-3 col-xs-3">
            <span class="help-block text-muted small-font"> {{form.date_use.label}}</span>
            {% for i in transactions %}
            <p>
            {{ i.date_use }}
            </p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}